# Test Profile Configuration

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/partydb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:/liquibase/base-changelog.xml


# Configuracoes do Amazon S3 DEV
aws.s3.access-key=${ACESS_KEY_S3}
aws.s3.secret-key=${SECRET_KEY_S3}
aws.s3.region=${BUCKET_REGION_S3}
aws.s3.bucket-name=${BUCKET_NAME_S3}

# propriedades de video
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

#prometheus
management.endpoints.web.exposure.include=prometheus,health,info
management.metrics.tags.application=api

api.security.token.secret=${SECRET_KEY_TOKEN:api-elovent-chave-secreta-segura}