# Prod Profile Configuration

# PostgreSQL Database Connection
spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Liquibase Settings
spring.liquibase.change-log=classpath:/liquibase/base-changelog.xml

# Configuracoes do Amazon S3
aws.s3.access-key=${ACESS_KEY_S3}
aws.s3.secret-key=${SECRET_KEY_S3}
aws.s3.region= sa-east-1
aws.s3.bucket-name=${BUCKET_NAME_S3}